### ISSUE TITLE
Inpainting is not working?

### ISSUE THREAD

**Issue by ovcharenkoo** [RobinKa/web-deep-image-prior#5]
Nice implementation! But I when I ran the script with selected inpainting option on the red car image the masked areas remained unchanged after 200 iterations. How many iterations should it take to complete the inpainting? 

Initial parameters were default except for the size of the image which I reduced to 128 x 128

**Comment by RobinKa** [comment]
Hey,

To see the results you need to click one of the small result image at the bottom which will show a bigger version. Here's an example: 
![image](https://user-images.githubusercontent.com/2614101/65614906-6009bd80-dfb0-11e9-87a1-3e3dd2762436.png)

This should indeed be made clearer. If this is not your issue please let me know. Thanks!

**Comment by ovcharenkoo** [comment]
Hi, thanks, I am just wondering why the masked spots do not get inpainted at whereas the rest of the image has already converged to about its original resolution? 

![image](https://user-images.githubusercontent.com/10777713/65678736-c42d8f80-e04b-11e9-90e8-cf73f47e65aa.png)

**Comment by RobinKa** [comment]
The white spots in the image are not actually masked, they are just white spots in the original image which can be used as an example for the inpainting. To mask something, use your mouse to draw on it (you can see on my screenshot some of the spots are shaded darker, this is the masked part which will get inpainted).

**Comment by ovcharenkoo** [comment]
Great, it works now, thanks! A prompt inviting user to manually mask these white spots would help 

![image](https://user-images.githubusercontent.com/10777713/65681258-69e2fd80-e050-11e9-8090-d296d598ba92.png)

**Comment by RobinKa** [comment]
Yes indeed. The entire UI should probably be remade into something more intuitive in general.
